POST {{API_URL}}/api/v1/customers
Content-Type: application/json

{
  "name":"César",
  "lastName":"Palma",
  "phone":"943928822",
    "user":{
    "email":"cemp2703@gmaill.com",
    "password":"12345678"
  }
}
