POST http://localhost:3000/api/v1/customers
Content-Type: application/json

{
  "name":"César",
  "lastName":"Rsdr3",
  "phone":"123456789",
    "user":{
    "email":"cemp.rsdr3@gmaill.com",
    "password":"123456789"
  }
}
