POST {{API_URL}}/api/v1/orders/add-item
Content-Type: application/json

{
  "orderId":1,
  "productId":1,
  "amount":5
}

# GET /api/v1/orders/:id/products/:id
# Content-Type: application/json
#
# {
#  "amount":5
# }
