POST http://localhost:3000/api/v1/products
Content-Type: application/json

{
  "name":"Camisajojo12233",
  "price":12,
  "description":"Camisa nueva2",
  "image":"http://placeimg.com/640/480",
  "categoryId":1
}
